Migrating to redux(Auth page)
spumony/quiz-app pull request #2
Opened 2020-06-22 12:28 UTC by spumony

- added gitignore file
- edited Adeonmaster's issues

2020-06-22 12:39 UTC, AdeonMaster requested changes

2020-06-22 12:39 UTC, AdeonMaster commented on .gitignore
> +node_modules
Add package lock file here too

2020-06-22 12:39 UTC, AdeonMaster commented on src/components/Logout/Logout.js
> +function mapDispatchToProps(dispatch) {
const mapDispatchToProps = { logout}

2020-06-22 12:39 UTC, AdeonMaster commented on src/containers/Auth/Auth.js
> +function mapDispatchToProps(dispatch) {
Simplify this

2020-06-22 12:39 UTC, AdeonMaster commented on src/containers/QuizCreator/QuizCreator.js
> +const mapStateToProps = state => {
Simplify this

2020-06-22 12:39 UTC, AdeonMaster commented on src/containers/QuizCreator/QuizCreator.js
> +const mapDispatchToProps = dispatch => {
Simplify

2020-06-22 12:44 UTC, spumony commented on src/containers/QuizCreator/QuizCreator.js
> +const mapStateToProps = state => {
how?

2020-06-22 13:35 UTC, AdeonMaster commented on src/containers/QuizCreator/QuizCreator.js
> +const mapStateToProps = state => {
```
const mapDispatchToProps = dispatch => {
  return {
    createQuizQestion: item => dispatch(createQuizQuestion(item)),
    finishCreateQuiz: () => dispatch(finishCreateQuiz())
  }
}
```
=>
```
const mapDispatchToProps = {
createQuizQestion,
finishCreateQuiz,
};
```

2020-06-23 08:36 UTC, AdeonMaster commented on firebase.json
> +  "hosting": {
You should combine this file with .firebaserc so .firebaserc will looki like:

```
{
  "projects": {
    "default": "react-quiz-468e0"
  },
  "hosting": {
    "public": "build",
    "ignore": [
      "firebase.json",
      "**/.*",
      "**/node_modules/**"
    ],
    "rewrites": [
      {
        "source": "**",
        "destination": "/index.html"
      }
    ]
  }
}
```

2020-06-23 08:37 UTC, AdeonMaster commented on .gitignore
> +package-lock.json
Empty line at the end please

2020-06-24 15:53 UTC, merged